### ISSUE TITLE
A simpler control flow api?

### ISSUE THREAD

**Issue by minoism** [hendraanggrian/kotlinpoet-ktx#1]
Now, if I need to generated:
```kotlin
forEach {
  println(it.toString())
}
```

I must call the following code:
```kotlin
beginFlow("forEach")
appendLine("println(it.toString())")
endFlow()
```

But I think there is a better way to do this:
```kotlin
flow("forEach") {
  appendLine("println(it.toString())")
}
```

Because I think this is more in line with dsl syntax~

**Comment by hanggrian** [comment]
Nice input, and only requires simple modification as well. Now the function name can be:
* `flow` - all for simplicity, but I fear that it might be too common that you could use the same name in your own source.
* `controlFlow` - in line with KotlinPoet's API.
* `appendFlow` - in line with `kotlin.text` since version 1.4.

Which one do you prefer?

**Comment by minoism** [comment]
Maybe `appendFlow` is prefer?

**Comment by minoism** [comment]
And I think `indent()` and `unindent()` methods can also be simplified by this way.

Like: 

```kotlin
indent {
  ...
  append(...)
}
```

**Comment by hanggrian** [comment]
Now I'm not so sure about this one, people use indent/unindent differently. For example, DSL method:

```kotlin
indent {
  append(...)
}
```

Can replace traditional method:

```kotlin
indent()
append(...)
unindent()
```

But what about:

```kotlin
indent()
append(...)
indent()
append(...)
unindent()

// or even

indent()
indent()
append(...)
append(...)
indent()
append(...)
unindent()
append(...)
unindent()
```

Different levels of the indentation you could customize makes DSL method not ideal replacement. Whereas the control flow, it is clear that you have to `endFlow` after `beginFlow`, there is no different variation of it. I'm open for rebuttal.

**Comment by minoism** [comment]
Could it be like this?
```kotlin
indent {
  append(...)
    indent {
      append(...)
    }

  indent {
    indent {
      append(...)
      append(...)
    indent {
      append(...)
    }
    append(...)
  }
}

// or even 
indent(space = 4)
```

Because I think that no matter how many times we indent, we may all need to cancel indentation eventually. Of course, we may only need to increase the api instead of completely replacing it.

**Comment by hanggrian** [comment]
Next update is scheduled to have these features, including the `indent` DSL. The traditional method to indent/unindent is still available, but control flow must be invoked with DSL.

Thanks for your input.
